pipelines:
  "cicd-demo":
    group: gocd
    label_template: "${git[:8]}"
    locking: off
    materials:
      git:
        git: git@github.com:FranciscoSokol0000/cicd-demo.git
    stages:
    - build:
        clean_workspace: true
        artifacts:
        - build:
            source: build/libs/*.jar
            destination: build/libs
        tasks:
        - exec:
            command: ./gradlew
            arguments:
            - build
        - exec:
            command: ./build.sh
        - exec:
            command: echo
            arguments:
              - "${GO_REVISION_GIT}"
